version: '3.8'

services:
  user-service:
    build: ./services/user-service
    ports:
      - "3100:3100"
    environment:
      - PORT=3100
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=inventory_db
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    ports:
      - "8090:80"
    depends_on:
      - user-service

volumes:
  db-data:
